openapi: 3.0.1
info:
  title: Contacts REST API
  description: Digital Postal System
  contact:
    url: 'https://github.com/igi64'
  license:
    name: Apache License 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  version: '0.3'
servers:
- url: '${BASE_SERVER_API_URL}'
  variables: {}
paths:
  '/contacts/search':
    get:
      tags:
      - contacts / search
      summary: Search all contacts (not implemented)
      operationId: searchAllContacts
      responses:
        '405':
          description: Invalid input
  '/people':
    get:
      tags:
      - people
      summary: List all people
      operationId: getAllPeople
      responses:
        '405':
          description: Invalid input
    post:
      tags:
      - people
      summary: Create a new person
      operationId: createPerson
      requestBody:
        description: Person to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPerson'
      responses:
        '405':
          description: Invalid input
  '/people/{id}':
    get:
      tags:
      - people
      summary: Get the specified person
      operationId: getPerson
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '405':
          description: Invalid input
    put:
      tags:
      - people
      summary: Update the specified person
      operationId: updatePerson
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Person to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePerson'
      responses:
        '405':
          description: Invalid input
    delete:
      tags:
      - people
      summary: Delete the specified person
      operationId: deletePerson
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '405':
          description: Invalid input
  '/groups':
    get:
      tags:
      - groups
      summary: List all groups
      operationId: getAllGroups
      responses:
        '405':
          description: Invalid input
    post:
      tags:
      - groups
      summary: Create a new group
      operationId: createGroup
      requestBody:
        description: Group to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewGroup'
      responses:
        '405':
          description: Invalid input
  '/groups/{id}':
    get:
      tags:
      - groups
      summary: Get the specified group
      operationId: getGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '405':
          description: Invalid input
    put:
      tags:
      - groups
      summary: Update the specified group
      operationId: updateGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Group to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGroup'
      responses:
        '405':
          description: Invalid input
    delete:
      tags:
      - groups
      summary: Delete the specified group
      operationId: deleteGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '405':
          description: Invalid input
  '/people/{id}/groups':
    get:
      tags:
      - people / groups
      summary: List all groups linked with person
      operationId: getAllGroupsLinkedWithPerson
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '405':
          description: Invalid input
  '/groups/{id}/people':
    get:
      tags:
      - groups / people
      summary: List all people in the specified group
      operationId: getAllPeopleInGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '405':
          description: Invalid input
  '/groups/{id}/people/add':
    put:
      tags:
        - groups / people
      summary: Add the specified list of people to the specified group
      operationId: addPeopleToGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: List of people to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeopleInGroup'
      responses:
        '200':
          description: Person added
        '403':
          description: Bad or missing API key
        '404':
          description: Person add error
  '/groups/{id}/people/remove':
    put:
      tags:
        - groups / people
      summary: Remove the specified list of people in the specified group
      operationId: removePeopleToGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: List of people to remove
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeopleInGroup'
      responses:
        '200':
          description: Person added
        '403':
          description: Bad or missing API key
        '404':
          description: Person add error
  '/groups/{id}/people/{personId}':
    get:
      tags:
      - groups / people
      summary: Get the specified person of the specified group
      operationId: getPersonInGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: personId
        in: path
        required: true
        schema:
          type: string
      responses:
        '405':
          description: Invalid input
components:
  schemas:
    Person:
      allOf:
      - $ref: '#/components/schemas/NewPerson'
      - required:
        - id
        properties:
          id:
            type: string
            format: uuidv4
    UpdatePerson:
      allOf:
      - $ref: '#/components/schemas/NewPerson'
      - required:
        - id
    NewPerson:
      properties:
        given_name:
          type: string
        surname:
          type: string
        email_address:
          type: string
    Group:
      allOf:
        - $ref: '#/components/schemas/NewGroup'
        - required:
            - id
          properties:
            id:
              type: string
              format: uuidv4
    UpdateGroup:
      allOf:
        - $ref: '#/components/schemas/NewGroup'
        - required:
            - id
    NewGroup:
      properties:
        name:
          type: string
    PeopleInGroup:
      type: object
      properties:
        people_ids:
          type: array
          items:
            $ref: '#/components/schemas/PeopleIds'
    PeopleIds:
      type: integer
