openapi: 3.0.1
info:
  title: Filters REST API
  description: Digital Postal System
  contact:
    url: 'https://github.com/igi64'
  license:
    name: Apache License 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  version: '0.3'
servers:
  - url: '${BASE_SERVER_API_URL}'
    variables: {}
paths:
  '/filters':
    get:
      tags:
        - filters
      summary: List all filters
      operationId: getAllFilters
      responses:
        '405':
          description: Invalid input
    post:
      tags:
        - filters
      summary: Create a new filter
      operationId: createFilter
      requestBody:
        description: Filter to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewFilter'
      responses:
        '405':
          description: Invalid input
  '/filters/{id}':
    get:
      tags:
        - filters
      summary: Get the specified filter
      operationId: getFilter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '405':
          description: Invalid input
    put:
      tags:
        - filters
      summary: Update the specified filter
      operationId: updateFilter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Filter to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFilter'
      responses:
        '405':
          description: Invalid input
    delete:
      tags:
        - filters
      summary: Delete the specified filter
      operationId: deleteFilter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '405':
          description: Invalid input
components:
  schemas:
    Filter:
      allOf:
        - $ref: '#/components/schemas/NewFilter'
        - required:
            - id
          properties:
            id:
              type: string
              format: uuidv4
    UpdateFilter:
      allOf:
        - $ref: '#/components/schemas/NewFilter'
        - required:
            - id
    NewFilter:
      properties:
        name:
          type: string
        criteria:
          type: string
        postal_labels:
          $ref: '#/components/schemas/PostalLabels'
        add_custom_label_ids:
          type: object
          properties:
            custom_label_ids:
              type: array
              items:
                $ref: '#/components/schemas/CustomLabelIds'
        remove_custom_label_ids:
          type: object
          properties:
            custom_label_ids:
              type: array
              items:
                $ref: '#/components/schemas/CustomLabelIds'
    CustomLabelIds:
      type: integer
    PostalLabels:
      type: object
      properties:
        done:
          type: boolean
          default: false
        archived:
          type: boolean
          default: false
        starred:
          type: boolean
          default: false
        important:
          type: boolean
          default: false
        chats:
          type: boolean
          default: false
        spam:
          type: boolean
          default: false
        unread:
          type: boolean
          default: false
        trash:
          type: boolean
          default: false
